name: Deploy to Firebase Hosting on merge
on: [push]

env:
  PROJECT_ID: w2c-space

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: cp -r dist functions
      - uses: aronep6/action-functions-deploy@1.0.0
        with:
          serviceAccountKey: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_W2C_SPACE }}"
          projectId: "${{ env.PROJECT_ID }}"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_W2C_SPACE }}'
          channelId: live
          projectId: w2c-space
