name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: cp -r dist functions
      - name: Install npm packages
        run: |
          cd functions
          npm install
          npm install firebase-tools
      - name: Deploy to Firebase
        run: |
          cd functions
          firebase deploy --only functions --project w2c-space
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_W2C_SPACE }}'
          channelId: live
          projectId: w2c-space
