name: Deploy to Firebase Hosting on merge
on: [push]



jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: cp -r dist functions
      - name: Deploy to Firebase
        uses: afgallo/deploy-firebase-functions@1.0.0
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_W2C_SPACE }}
          TARGET: w2c-space
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_W2C_SPACE }}'
          channelId: live
          projectId: w2c-space
