name: Generate Sitemap

on:
  schedule:
    - cron: '0 0 * * *' 

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Generate Sitemap Script
        run: node generate-sitemap.js
        
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add ./public/sitemap.xml
          git commit -m "Updated sitemap.xml"
          git push https://$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git HEAD:main
